### ISSUE TITLE
Use ~/.ssh/config for sites configuration

### ISSUE THREAD

**Issue by jhit** [muriloventuroso/easyssh#18]
It would be nice If easyssh could read and write the openssh config file. I have a large set of sites in there and synchronize this file between computers.

I think using this config file would make easyssh a great tool for more people.

**Comment by muriloventuroso** [comment]
Thanks for the feedback! I'm adding some tools to EasySSH so that it supports all or much of the ssh command-line features. And this synchronization with ~ / .ssh / config would be awesome.

After finalizing these additional features I am thinking of implementing synchronization between the configuration files. I can not save the configuration of the EasySSH hosts in ~ / .ssh / config because the application has several extra settings that would be polluting the ssh configuration. But selective syncing would be cool.

Thanks again for the feedback. I will inform you of the progress of the implementation in this commit.

**Comment by jhit** [comment]
Hi @muriloventuroso 
Sounds great. Maybe you could possibly split settings. The settings supportet by ssh config file save there (might be a optional setting in the app) and what is not supportet can go to the json like it is now. A Link between both files could be done by the entry name of the ssh config entry.

**Comment by jhit** [comment]
Thanks for implementing this. As a small sign of gratitude, I updated the German translation.
