### ISSUE TITLE
[Bug report] Unable to add private key from /home/user/.ssh

### ISSUE THREAD

**Issue by kakogoxepa** [muriloventuroso/easyssh#92]
**Very bad bug**

Unable to add private key from /home/username/.ssh/ directory on version 1.6.5 and 1.6.6

**Comment by kakogoxepa** [comment]
@muriloventuroso see bug on this video 
[video.mp4.zip](https://github.com/muriloventuroso/easyssh/files/4143909/video.mp4.zip)

**Comment by muriloventuroso** [comment]
EasySSH uses a GTK native FileChooser, so I believe this Bug is related to the elementaryOS implementation. I did the test on my machine and got the same result. However, if you use the shortcut Ctrl + H to show the hidden files and folders, I can enter the .ssh folder using the mouse.
I will research if there is any bug already reported that describes this behavior in the elementary repositories.

**Comment by kakogoxepa** [comment]
@muriloventuroso Indeed, the combination of Ctl + H helped to see the .ssh folder and with the help of the mouse cursor I was able to enter it. Thanks you !!!
