### ISSUE TITLE
Unable to build project on ArchLinux

### ISSUE THREAD

**Issue by JeffLabonte** [muriloventuroso/easyssh#95]
Hey there! 

I just wanted to you know that the code compiling on systems that runs a more bleeding edge close.

Here is the ouput:

```
ound ninja-1.10.0 at /usr/bin/ninja
ninja: Entering directory `build'
[6/27] Compiling Vala source ../src/Application.vala ../src/Host.vala ../src/Account.vala ../s...../src/Widgets/SearchToolbar.vala ../src/Widgets/BookmarksPopover.vala ../src/Widgets/Tab.vala
FAILED: com.github.muriloventuroso.easyssh@exe/src/Application.c com.github.muriloventuroso.easyssh@exe/src/Host.c com.github.muriloventuroso.easyssh@exe/src/Account.c com.github.muriloventuroso.easyssh@exe/src/Bookmark.c com.github.muriloventuroso.easyssh@exe/src/MainWindow.c com.github.muriloventuroso.easyssh@exe/src/Services/Settings.c com.github.muriloventuroso.easyssh@exe/src/Views/SourceListView.c com.github.muriloventuroso.easyssh@exe/src/Widgets/TerminalBox.c com.github.muriloventuroso.easyssh@exe/src/Widgets/Welcome.c com.github.muriloventuroso.easyssh@exe/src/Widgets/WelcomeAccounts.c com.github.muriloventuroso.easyssh@exe/src/Widgets/HeaderBar.c com.github.muriloventuroso.easyssh@exe/src/Widgets/ConnectionEditor.c com.github.muriloventuroso.easyssh@exe/src/Widgets/AccountEditor.c com.github.muriloventuroso.easyssh@exe/src/Widgets/Connection.c com.github.muriloventuroso.easyssh@exe/src/Widgets/ErrorRevealer.c com.github.muriloventuroso.easyssh@exe/src/Widgets/Preferences.c com.github.muriloventuroso.easyssh@exe/src/Widgets/TerminalWidget.c com.github.muriloventuroso.easyssh@exe/src/Widgets/SearchToolbar.c com.github.muriloventuroso.easyssh@exe/src/Widgets/BookmarksPopover.c com.github.muriloventuroso.easyssh@exe/src/Widgets/Tab.c
valac -C --debug --debug --define WITH_GPG --pkg vte-2.91 --pkg json-glib-1.0 --pkg granite --pkg gtk+-3.0 --pkg glib-2.0 --pkg gee-0.8 --color=always --directory com.github.muriloventuroso.easyssh@exe --basedir ../ --gresources=../data/com.github.muriloventuroso.easyssh.gresource.xml ../src/Application.vala ../src/Host.vala ../src/Account.vala ../src/Bookmark.vala ../src/MainWindow.vala ../src/Services/Settings.vala ../src/Views/SourceListView.vala ../src/Widgets/TerminalBox.vala ../src/Widgets/Welcome.vala ../src/Widgets/WelcomeAccounts.vala ../src/Widgets/HeaderBar.vala ../src/Widgets/ConnectionEditor.vala ../src/Widgets/AccountEditor.vala ../src/Widgets/Connection.vala ../src/Widgets/ErrorRevealer.vala ../src/Widgets/Preferences.vala ../src/Widgets/TerminalWidget.vala ../src/Widgets/SearchToolbar.vala ../src/Widgets/BookmarksPopover.vala ../src/Widgets/Tab.vala
../src/Services/Settings.vala:53.17-53.37: warning: unhandled error `GLib.Error'
                file.make_directory();
                ^^^^^^^^^^^^^^^^^^^^^
../src/Widgets/TerminalWidget.vala:121.21-121.30: warning: Gtk.Menu.popup has been deprecated since 3.22
../src/Widgets/TerminalWidget.vala:174.17-174.31: warning: Vte.Terminal.spawn_sync has been deprecated since 0.48
../src/Widgets/TerminalWidget.vala:181.25-181.39: warning: Vte.Terminal.spawn_sync has been deprecated since 0.48
../src/Widgets/TerminalWidget.vala:174.17-175.101: warning: unhandled error `GLib.Error'
../src/Widgets/TerminalWidget.vala:219.33-219.46: error: Argument 1: Cannot convert from `char[]' to `unowned uint8[]?'
                this.feed_child(cmd.to_utf8 ());
                                ^^^^^^^^^^^^^^
../src/Widgets/SearchToolbar.vala:97.21-97.42: warning: Vte.Terminal.search_set_gregex has been deprecated since 0.46
../src/Widgets/TerminalBox.vala:103.33-103.46: error: Argument 1: Cannot convert from `char[]' to `unowned uint8[]?'
                term.feed_child(cmd.to_utf8 ());
                                ^^^^^^^^^^^^^^
../src/Widgets/TerminalBox.vala:210.33-210.48: error: Argument 1: Cannot convert from `char[]' to `unowned uint8[]?'
                term.feed_child(n_cmd.to_utf8 ());
                                ^^^^^^^^^^^^^^^^
../src/Widgets/TerminalBox.vala:201.33-201.46: error: Argument 1: Cannot convert from `char[]' to `unowned uint8[]?'
                term.feed_child(cmd.to_utf8 ());
                                ^^^^^^^^^^^^^^
../src/Views/SourceListView.vala:1055.21-1055.34: warning: unhandled error `GLib.Error'
                    file.delete ();
                    ^^^^^^^^^^^^^^
../src/Views/SourceListView.vala:1057.49-1057.97: warning: unhandled error `GLib.Error'
                var dos = new DataOutputStream (file.create (FileCreateFlags.REPLACE_DESTINATION));
                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../src/Views/SourceListView.vala:1059.17-1059.37: warning: unhandled error `GLib.IOError'
                dos.put_string (data);
                ^^^^^^^^^^^^^^^^^^^^^
../src/Views/SourceListView.vala:1066.25-1066.42: warning: unhandled error `GLib.Error'
                        file_ssh.delete ();
                        ^^^^^^^^^^^^^^^^^^
../src/Views/SourceListView.vala:1068.57-1068.109: warning: unhandled error `GLib.Error'
                    var dos_ssh = new DataOutputStream (file_ssh.create (FileCreateFlags.REPLACE_DESTINATION));
                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../src/Views/SourceListView.vala:1069.21-1069.56: warning: unhandled error `GLib.IOError'
                    dos_ssh.put_string (data_ssh_config);
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../src/Views/SourceListView.vala:1108.21-1108.34: warning: unhandled error `GLib.Error'
                    file.delete ();
                    ^^^^^^^^^^^^^^
../src/Views/SourceListView.vala:1110.49-1110.97: warning: unhandled error `GLib.Error'
                var dos = new DataOutputStream (file.create (FileCreateFlags.REPLACE_DESTINATION));
                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../src/Views/SourceListView.vala:1112.17-1112.37: warning: unhandled error `GLib.IOError'
                dos.put_string (data);
                ^^^^^^^^^^^^^^^^^^^^^
../src/Views/SourceListView.vala:1149.21-1149.34: warning: unhandled error `GLib.Error'
                    file.delete ();
                    ^^^^^^^^^^^^^^
../src/Views/SourceListView.vala:1151.49-1151.97: warning: unhandled error `GLib.Error'
                var dos = new DataOutputStream (file.create (FileCreateFlags.REPLACE_DESTINATION));
                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../src/Views/SourceListView.vala:1153.17-1153.37: warning: unhandled error `GLib.IOError'
                dos.put_string (data);
                ^^^^^^^^^^^^^^^^^^^^^
../src/Views/SourceListView.vala:140.13-140.27: warning: Gtk.Widget.margin_left has been deprecated since 3.12
../src/MainWindow.vala:35.9-35.42: warning: EasySSH.MainWindow.application hides inherited property `Gtk.Window.application'. Use the `new' keyword if hiding was intentional
        public Gtk.Application application { get; construct; }
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../src/MainWindow.vala:429.13-429.82: warning: unhandled error `GLib.SpawnError'
            Process.spawn_command_line_async (default_filemanager + " " + command);
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../src/MainWindow.vala:239.13-242.41: warning: unhandled error `GLib.SpawnError'
../src/MainWindow.vala:249.13-252.41: warning: unhandled error `GLib.SpawnError'
../src/MainWindow.vala:137.32-137.46: warning: Gtk.ActionGroup has been deprecated since 3.10
../src/MainWindow.vala:152.22-152.34: warning: Gtk.UIManager has been deprecated since 3.10
Compilation failed: 4 error(s), 25 warning(s)

```

**Comment by Kkeller83** [comment]
Similiar her on Manjaro: 

../src/MainWindow.vala:25.9-25.31: warning: `Gtk.UIManager' has been deprecated since 3.10
../src/MainWindow.vala:25.40-25.51: warning: `Gtk.UIManager' has been deprecated since 3.10
../src/MainWindow.vala:59.9-59.43: warning: `Gtk.ActionGroup' has been deprecated since 3.10
../src/Widgets/TerminalWidget.vala:121.21-121.30: warning: `Gtk.Menu.popup' has been deprecated since 3.22
../src/Widgets/TerminalWidget.vala:174.17-174.31: warning: `Vte.Terminal.spawn_sync' has been deprecated since 0.48
../src/Widgets/TerminalWidget.vala:181.25-181.39: warning: `Vte.Terminal.spawn_sync' has been deprecated since 0.48
../src/Widgets/TerminalWidget.vala:174.17-175.101: warning: unhandled error `GLib.Error'
../src/Widgets/TerminalWidget.vala:217.33-217.35: error: Argument 1: Cannot convert from `unowned string' to `unowned uint8[]?'
                this.feed_child(cmd, cmd.length);
                                ^^^
../src/Widgets/TerminalWidget.vala:217.17-217.48: error: 1 extra arguments for `void Vte.Terminal.feed_child (uint8[]?)'
                this.feed_child(cmd, cmd.length);
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../src/Widgets/SearchToolbar.vala:97.21-97.42: warning: `Vte.Terminal.search_set_gregex' has been deprecated since 0.46
../src/Widgets/TerminalBox.vala:101.33-101.35: error: Argument 1: Cannot convert from `unowned string' to `unowned uint8[]?'
                term.feed_child(cmd, cmd.length);
                                ^^^
../src/Widgets/TerminalBox.vala:101.17-101.48: error: 1 extra arguments for `void Vte.Terminal.feed_child (uint8[]?)'
                term.feed_child(cmd, cmd.length);
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../src/Widgets/TerminalBox.vala:208.33-208.37: error: Argument 1: Cannot convert from `unowned string' to `unowned uint8[]?'
                term.feed_child(n_cmd, cmd.length);
                                ^^^^^
../src/Widgets/TerminalBox.vala:208.17-208.50: error: 1 extra arguments for `void Vte.Terminal.feed_child (uint8[]?)'
                term.feed_child(n_cmd, cmd.length);
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../src/Widgets/TerminalBox.vala:199.33-199.35: error: Argument 1: Cannot convert from `unowned string' to `unowned uint8[]?'
                term.feed_child(cmd, cmd.length);
                                ^^^
../src/Widgets/TerminalBox.vala:199.17-199.48: error: 1 extra arguments for `void Vte.Terminal.feed_child (uint8[]?)'
                term.feed_child(cmd, cmd.length);
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../src/Views/SourceListView.vala:1055.21-1055.34: warning: unhandled error `GLib.Error'
                    file.delete ();
                    ^^^^^^^^^^^^^^
../src/Views/SourceListView.vala:1057.49-1057.97: warning: unhandled error `GLib.Error'
                var dos = new DataOutputStream (file.create (FileCreateFlags.REPLACE_DESTINATION));
                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../src/Views/SourceListView.vala:1059.17-1059.37: warning: unhandled error `GLib.IOError'
                dos.put_string (data);
                ^^^^^^^^^^^^^^^^^^^^^
../src/Views/SourceListView.vala:1066.25-1066.42: warning: unhandled error `GLib.Error'
                        file_ssh.delete ();
                        ^^^^^^^^^^^^^^^^^^
../src/Views/SourceListView.vala:1068.57-1068.109: warning: unhandled error `GLib.Error'
                    var dos_ssh = new DataOutputStream (file_ssh.create (FileCreateFlags.REPLACE_DESTINATION));
                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../src/Views/SourceListView.vala:1069.21-1069.56: warning: unhandled error `GLib.IOError'
                    dos_ssh.put_string (data_ssh_config);
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../src/Views/SourceListView.vala:1108.21-1108.34: warning: unhandled error `GLib.Error'
                    file.delete ();
                    ^^^^^^^^^^^^^^
../src/Views/SourceListView.vala:1110.49-1110.97: warning: unhandled error `GLib.Error'
                var dos = new DataOutputStream (file.create (FileCreateFlags.REPLACE_DESTINATION));
                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../src/Views/SourceListView.vala:1112.17-1112.37: warning: unhandled error `GLib.IOError'
                dos.put_string (data);
                ^^^^^^^^^^^^^^^^^^^^^
../src/Views/SourceListView.vala:1149.21-1149.34: warning: unhandled error `GLib.Error'
                    file.delete ();
                    ^^^^^^^^^^^^^^
../src/Views/SourceListView.vala:1151.49-1151.97: warning: unhandled error `GLib.Error'
                var dos = new DataOutputStream (file.create (FileCreateFlags.REPLACE_DESTINATION));
                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../src/Views/SourceListView.vala:1153.17-1153.37: warning: unhandled error `GLib.IOError'
                dos.put_string (data);
                ^^^^^^^^^^^^^^^^^^^^^
../src/Views/SourceListView.vala:140.13-140.27: warning: `Gtk.Widget.margin_left' has been deprecated since 3.12
../src/MainWindow.vala:35.9-35.42: warning: EasySSH.MainWindow.application hides inherited property `Gtk.Window.application'. Use the `new' keyword if hiding was intentional
        public Gtk.Application application { get; construct; }
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../src/MainWindow.vala:429.13-429.82: warning: unhandled error `GLib.SpawnError'
            Process.spawn_command_line_async (default_filemanager + " " + command);
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../src/MainWindow.vala:239.13-242.41: warning: unhandled error `GLib.SpawnError'
../src/MainWindow.vala:249.13-252.41: warning: unhandled error `GLib.SpawnError'
../src/MainWindow.vala:137.32-137.46: warning: `Gtk.ActionGroup' has been deprecated since 3.10
../src/MainWindow.vala:152.22-152.34: warning: `Gtk.UIManager' has been deprecated since 3.10
Compilation failed: 8 error(s), 28 warning(s)
ninja: build stopped: subcommand failed.

**Comment by iwex** [comment]
Bump

**Comment by muriloventuroso** [comment]
Please repeat the build using the "ubuntu-bionic-patched-vte" option.
This is a compatibility issue between versions of lib Gtk.VTE

**Comment by Kkeller83** [comment]
meson -Dubuntu-bionic-patched-vte=false -Dlibunity=false build --prefix=/usr   gets me this


                ^^^^^^^^^^^^^^^^^^
../src/Views/SourceListView.vala:1069.57-1069.109: warning: unhandled error `GLib.Error'
                    var dos_ssh = new DataOutputStream (file_ssh.create (FileCreateFlags.REPLACE_DESTINATION));
                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../src/Views/SourceListView.vala:1070.21-1070.56: warning: unhandled error `GLib.IOError'
                    dos_ssh.put_string (data_ssh_config);
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../src/Views/SourceListView.vala:1109.21-1109.34: warning: unhandled error `GLib.Error'
                    file.delete ();
                    ^^^^^^^^^^^^^^
../src/Views/SourceListView.vala:1111.49-1111.97: warning: unhandled error `GLib.Error'
                var dos = new DataOutputStream (file.create (FileCreateFlags.REPLACE_DESTINATION));
                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../src/Views/SourceListView.vala:1113.17-1113.37: warning: unhandled error `GLib.IOError'
                dos.put_string (data);
                ^^^^^^^^^^^^^^^^^^^^^
../src/Views/SourceListView.vala:1150.21-1150.34: warning: unhandled error `GLib.Error'
                    file.delete ();
                    ^^^^^^^^^^^^^^
../src/Views/SourceListView.vala:1152.49-1152.97: warning: unhandled error `GLib.Error'
                var dos = new DataOutputStream (file.create (FileCreateFlags.REPLACE_DESTINATION));
                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../src/Views/SourceListView.vala:1154.17-1154.37: warning: unhandled error `GLib.IOError'
                dos.put_string (data);
                ^^^^^^^^^^^^^^^^^^^^^
../src/Views/SourceListView.vala:140.13-140.27: warning: `Gtk.Widget.margin_left' has been deprecated since 3.12
../src/MainWindow.vala:35.9-35.42: warning: EasySSH.MainWindow.application hides inherited property `Gtk.Window.application'. Use the `new' keyword if hiding was intentional
        public Gtk.Application application { get; construct; }
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../src/MainWindow.vala:432.13-432.82: warning: unhandled error `GLib.SpawnError'
            Process.spawn_command_line_async (default_filemanager + " " + command);
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../src/MainWindow.vala:242.13-245.41: warning: unhandled error `GLib.SpawnError'
../src/MainWindow.vala:252.13-255.41: warning: unhandled error `GLib.SpawnError'
../src/MainWindow.vala:133.13-133.43: warning: `Gtk.Settings.gtk_menu_bar_accel' has been deprecated since 3.10
../src/MainWindow.vala:140.32-140.46: warning: `Gtk.ActionGroup' has been deprecated since 3.10
../src/MainWindow.vala:155.22-155.34: warning: `Gtk.UIManager' has been deprecated since 3.10

**Comment by Kkeller83** [comment]
Also after changing the build options in the meson_options.txt libunity and vte to false.. I get this :+1: 


./src/Widgets/TerminalWidget.vala:174.17-175.101: warning: unhandled error `GLib.Error'
../src/Widgets/TerminalWidget.vala:219.33-219.46: error: Argument 1: Cannot convert from `char[]' to `unowned uint8[]?'
                this.feed_child(cmd.to_utf8 ());
                                ^^^^^^^^^^^^^^
../src/Widgets/SearchToolbar.vala:97.21-97.42: warning: `Vte.Terminal.search_set_gregex' has been deprecated since 0.46
../src/Widgets/TerminalBox.vala:107.33-107.46: error: Argument 1: Cannot convert from `char[]' to `unowned uint8[]?'
                term.feed_child(cmd.to_utf8 ());
                                ^^^^^^^^^^^^^^
../src/Widgets/TerminalBox.vala:214.33-214.48: error: Argument 1: Cannot convert from `char[]' to `unowned uint8[]?'
                term.feed_child(n_cmd.to_utf8 ());
                                ^^^^^^^^^^^^^^^^
../src/Widgets/TerminalBox.vala:205.33-205.46: error: Argument 1: Cannot convert from `char[]' to `unowned uint8[]?'
                term.feed_child(cmd.to_utf8 ());
                                ^^^^^^^^^^^^^^
../src/Views/SourceListView.vala:1056.21-1056.34: warning: unhandled error `GLib.Error'
